packages:
 - wget
 - curl
 - htop
 - nginx
 - python3
 - python3-venv
 - python3-pip

# nginx:
#   listen_port: "80"
#   server_name: "myserver.example.com"

# server_info_app:
#   api_workdir: /opt/server-info-api
#   api_venv_path: /opt/server-info-api/venv
#   api_host: 127.0.0.1
#   api_port: 8000

server_info_api_workdir: /opt/server-info-api
server_info_api_venv_path: /opt/server-info-api/venv
server_info_api_host: 127.0.0.1
server_info_api_port: 8000

server_info_target_dir: /var/www/server-info
server_info_index_file: index.html
server_info_page_title: "Server info"
server_info_header: "Server info"

server_info_nginx_listen: "80"
server_info_nginx_server_name: "myserver.example.com"
